export {
  BEHAVIOR_TREE_ID_POLICIES,
  CONFIG_ROOT_FIELDS,
  SEVERITIES,
  createInitConfig,
  fileMatchesPattern,
  getDefaultBtxmlConfig,
  getDefaultResolvedBtxmlConfig,
  getEffectiveConfigForFile,
  getEffectiveConfigForUri,
  matchOverrides,
  mergeBtxmlConfig,
  normalizeBtxmlConfig,
  parseBtxmlConfig,
} from "@btxml/config";

export type {
  ConfigDiagnostic,
  ConfigNormalizeResult,
  ConfigParseResult,
  ConfigSeverity,
  EffectiveFileConfig,
  RawBtxmlConfig,
  RawBtxmlConfigInput,
  RawFilesConfig,
  RawFormatterConfig,
  RawLinterConfig,
  RawLinterSuppressionsConfig,
  RawModelsConfig,
  RawOverrideConfig,
  RawResolverConfig,
  RawResolverIncludesConfig,
  ResolvedBtxmlConfig,
  ResolvedFilesConfig,
  ResolvedFormatterConfig,
  ResolvedLinterConfig,
  ResolvedLinterSuppressionsConfig,
  ResolvedModelsConfig,
  ResolvedOverrideConfig,
  ResolvedResolverConfig,
  ResolvedResolverIncludesConfig,
  RuleConfig,
} from "@btxml/config";
