export {
  parseBtXml,
  formatBtXml,
  findIncompleteOpenStartTag,
  inspectXmlCursor,
  findElementAt,
  findJustClosedStartTag,
  findOpenStartTagAtSlash,
  getAttribute,
  getElementChildren,
  getElementText,
  isElement,
  positionAt,
  scanXmlPrefix,
  walkElements,
} from "@btxml/syntax";

export type {
  BtDocument,
  BtDocumentKind,
  BtXmlAttribute,
  BtXmlComment,
  BtXmlElement,
  BtXmlNode,
  BtXmlText,
  FormatOptions,
  FormatResult,
  ParseOptions,
  ParseResult,
  TextLikeDocument,
  XmlClosedStartTag,
  XmlCursorContext,
  XmlOpenStartTag,
  XmlPrefixContext,
  XmlPrefixScanResult,
  XmlDeclaration,
} from "@btxml/syntax";
