export { createLanguageService } from "./service.js";
export { createWorkspaceService } from "./workspace-service.js";

export type {
  BtEditorService,
  BtEditorServiceOptions,
  CodeAction,
  CodeActionsInput,
  CodeActionsResult,
  ChildCapabilityReason,
  ChildCapabilityResult,
  CompletionInput,
  CompletionItem,
  CompletionItemKind,
  CompletionResult,
  DefinitionInput,
  DefinitionResult,
  DiagnosticsInput,
  DiagnosticsResult,
  DocumentSymbol,
  DocumentSymbolsInput,
  DocumentSymbolsResult,
  DirEntry,
  FileStat,
  FormattingInput,
  FormattingResult,
  HoverInput,
  HoverResult,
  LanguageService,
  LanguageServiceOptions,
  Location,
  NodeCatalogResult,
  NodeUsageAtResult,
  NodeModelResult,
  PortInfoResult,
  ReferencesInput,
  ReferencesResult,
  SemanticNodeResult,
  SemanticDocumentViewResult,
  WorkspaceDiagnosticsResult,
  WorkspaceHost,
  WorkspaceServiceOptions,
} from "./public-types.js";
